
[package]
name = "mlang_semantic"
version = "0.0.1"
edition.workspace = true

[dependencies]
lsp_definition = { workspace = true }
line_index = { workspace = true }
mlang_syntax = { workspace = true }
mlang_parser = { workspace = true }

biome_rowan = { workspace = true }
unicase = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
tower-lsp = { workspace = true }
